routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@index')->name('home');
Route::get('/shop', 'SiteController@shop')->name('shop');
Route::get('/about', 'SiteController@about')->name('about');
Route::get('/faqs', 'SiteController@faqs')->name('faqs');
Route::get('/contact', 'SiteController@contact')->name('contact');
Route::get('/adminSite', 'SiteController@adminSite')->name('adminSite');

Auth::routes();

Route::prefix('admin')->group(function () {

	Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');

//	Reset Admin Password
	Route::prefix('password')->group(function () {
		Route::get('/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');   // step 1
		Route::post('/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');    // step 2
		Route::get('/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');   // step 3
		Route::post('/reset', 'Auth\AdminResetPasswordController@reset');   // step 4
	});


});
Route::prefix('user')->group(function () {
	//	Reset Password
	Route::prefix('password')->group(function () {
		Route::get('/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');   // step 1
		Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');    // step 2
		Route::get('/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');   // step 3
		Route::post('/reset', 'Auth\ResetPasswordController@reset');    // step 4
	});
});

Route::prefix('collection')->group(function () {

});
Route::prefix('product')->group(function () {
});

Route::resource('product', 'ProductController');
Route::resource('collection', 'CollectionController');
Route::resource('user', 'UserController');
Route::resource('admin', 'AdminController');

resources/views/admin/layouts/footer.blade.php
<footer>
	<div class="navbar navbar-default navbar-fixed-bottom footer">
		<ul class="nav navbar-nav visible-xs-block">
			<li><a class="text-center collapsed" data-toggle="collapse" data-target="#footer"><i
							class="icon-circle-up2"></i></a></li>
		</ul>

		<div class="navbar-collapse collapse" id="footer">
			<div class="navbar-text">
				&copy; 2017. <a href="{{route('home')}}" class="navbar-link">theLine</a>
				by <a class="navbar-link" target="_blank">LonelyTomb</a>
			</div>

			<div class="navbar-right">
				<ul class="nav navbar-nav">
					<li><a href="#">About</a></li>
					<li><a href="#">Terms</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>

resources/views/admin/layouts/header.blade.php
<div class="navbar navbar-inverse">
	<div class="navbar-header">
		<a class="navbar-brand" href="index.html">
			{{--<img src="theLine-01-03-black2.png" alt="">--}}
		</a>

		<ul class="nav navbar-nav pull-right visible-xs-block">
			<li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
			<li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
		</ul>
	</div>

	<div class="navbar-collapse collapse" id="navbar-mobile">
		<ul class="nav navbar-nav">
			<li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a>
			</li>
		</ul>

		<ul class="nav navbar-nav navbar-right">

			<li class="dropdown dropdown-user">
				<a class="dropdown-toggle" data-toggle="dropdown">
					{{--<img src="assets/images/image.png" alt="">--}}
					@auth
					<span>Firstname</span>
					@endauth
					<i class="caret"></i>
				</a>

				<ul class="dropdown-menu dropdown-menu-right">
					<li><a href="#"><i class="icon-user-plus"></i> My profile</a></li>
					<li><a href="?logOut&admin"><i class="icon-switch2"></i> Logout</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>
<!-- /main navbar -->


<!-- Page header -->
<div class="page-header">
	<div class="breadcrumb-line">
		<ul class="breadcrumb">
			<li><a href="{{route('admin.index')}}"><i class="icon-home2 position-left"></i>
					Home</a></li>
			<li class="active">Dashboard</li>
		</ul>

	</div>
	<br>
	<br>
	<br>
</div>

resources/views/admin/layouts/sidebar.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-main">
	<div class="sidebar-fixed ">
		<div class="sidebar-content">

			<!-- Main navigation -->
			<div class="sidebar-category sidebar-category-visible">
				<div class="category-title h6">
					<ul class="icons-list">
						<li><a href="#" data-action="collapse"></a></li>
					</ul>
				</div>

				<div class="category-content sidebar-user">
					<div class="media">
						<a href="#" class="media-left">
							{{--<img src="/assets/images/image.png" class="img-circle img-sm" alt="">--}}
						</a>
						<div class="media-body">
							<span class="media-heading text-semibold">First name</span>
							<div class="text-size-mini text-muted">
							</div>
						</div>

					</div>
				</div>
				<div class="category-content no-padding">
					<ul class="navigation navigation-main navigation-accordion">

						<!-- Main -->
						<li class="navigation-header"><span>Main</span> <i class="icon-menu" title="Main pages"></i>
						</li>
						<li><a href="{{route('adminSite')}}"><i class="icon-home4"></i>
								<span>Dashboard</span></a></li>

						<li><a href="#"><i class="icon-cog3"></i>
								<span>Manage</span></a>
							<ul>
								<li><a href="#"><i class=" icon-user-tie"></i><span>Admin</span></a>
									<ul>
										<li class="{{Route::is('admin/create') ? 'active' : ''}}">
											<a href="{{route('admin.create')}}"><span>Create Admin</span></a>
										</li>
										<li class="{{Route::is('admin/index') ? 'active' : ''}}">
											<a href="{{route('admin.index')}}"><span></span>Update
												Admin</a>
										</li>
									</ul>
								</li>
								<li><a href="#"><i class="icon-user"></i><span>Client</span></a>
									<ul>
										<li class
										    ="{{Route::is('user') ? 'active' : ''}}">
											<a href="{{route('user.index')}}"><i></i><span>View Clients Purchases</span></a>
										</li>
									</ul>
								</li>
							</ul>
						</li>

						<li>
							<a href="#"><i class="icon-database-add"></i> <span>Create</span></a>
							<ul>
								<li class="{{Route::is('collection/create') ? 'active' : ''}}">
									<a href="{{route('collection.create')}}">New Collection</a>
								</li>
								<li class="{{Route::is('product/create') ? 'active' : ''}}">
									<a href="{{route('product.create')}}">New Product</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="#"><i class=" icon-database-menu"></i> <span>View</span></a>
							<ul>
								<li class="{{Route::is('collection/index') ? 'active' : ''}}">
									<a href="{{route('collection.index')}}">All Collections</a>
								</li>
								<li class="{{Route::is('product/index') ? 'active' : ''}}">
									<a href="{{route('product.index')}}">All Products</a>
								</li>
								<li class
								    ="{{Route::is('product/report') ? 'active' : ''}}"><a
											href="">Products
										Reports</a></li>
							</ul>
						</li>
						<li>
							<a href="#"><i class=" icon-database-edit2"></i> <span>Update</span></a>
							<ul>
								<li class="{{Route::is('collection/index') ? 'active' : ''}}">
									<a href="{{route('collection.index')}}">Existing Collections</a>
								</li>
								<li class="{{Route::is('product/index') ? 'active' : ''}}">
									<a href="{{route('product.index')}}">ExistingProducts</a></li>
							</ul>
						</li>
						<li>
							<a href="#"><i class=" icon-database-remove"></i> <span>Delete</span></a>
							<ul>
								<li class="{{Route::is('collection/index') ? 'active' : ''}}">
									<a href="{{route('collection.index')}}">Collection</a>
								</li>
								<li class="{{Route::is('product/index') ? 'active' : ''}}">
									<a href="{{route('product.index')}}">Product</a>
								</li>
							</ul>
						</li>
						<!-- /main -->

					</ul>
				</div>
			</div>
			<!-- /main navigation -->

		</div>
	</div>
</div>
<!-- /main sidebar -->